### ISSUE TITLE
log broken

### ISSUE THREAD

**Issue by laurobmb** [reighnman/Graylog_Content_Pack_WinDNS#5]
hello !!! :)

LOG information is coming broken, is there any way to fix this?

(nxlog installed windows server 2012)

"2/22/2016 2:45:09 PM 0EC0 PACKET  0000004D68612250 UDP Rcv 192.1"

thank you!!

**Comment by reighnman** [comment]
I will look into this with the 2.0 release.

**Comment by wjanowiak** [comment]
Understood you will look at in 2.0 but any clues into why for 1.3? Happy to help debug

**Comment by wjanowiak** [comment]
I got this working - couple issues I found.

1) "full_message" field was not being pulled into graylog for the DNS entries
2) The "message" field was being truncated like above
3) The extractors were not matching anything since the "full_message" field was missing.

There is additional config required in the newer version of nxlog to get the entire message sent to graylog. More info can be found in this thread:

https://groups.google.com/forum/m/#!topic/graylog2/0OTyDgSj3nA

I added "ShortMessageLength -1" to the nxlog config

`<Extension _gelf>`
    `Module      xm_gelf`
   `ShortMessageLength  -1` << this field
`</Extension>`

This fixed the messages coming in truncated but I still have not figured out the problem with the "full_message" field. To work around this until this is resolved - I removed the extractors and re-added them by adjusting the "target_field" and "source_field" to read "message" instead of "full_message".

**Comment by reighnman** [comment]
Good find, I have not tested with the latest version of nxlog yet but will note it.

Do you have full_message enabled on the input?

**Comment by wjanowiak** [comment]
That was the interesting part - I am not presented that option for GELF UDP inputs. Whether I edit the existing one or create a new one (see attached screenshot). The checkbox for storing "full_message" is present for Syslog inputs, but none of the GELF ones. 

I am running version 1.3.3 - just installed a few days ago.

![screen shot 2016-03-09 at 5 31 44 pm](https://cloud.githubusercontent.com/assets/1671525/13656612/300ef37e-e61d-11e5-9aaa-bde5c2af3eff.png)

**Comment by reighnman** [comment]
Readme has been updated to include this in the config.

ShortMessageLength -1

**Comment by eduham** [comment]
i have got the same problem like wjanowiak. is there already a solution?
